### ISSUE TITLE
Make first PyPI release.

### ISSUE THREAD

**Issue by gregmuellegger** [team23/django_backend#1]
We should get one release out to ease integration with new projects.

**Comment by ddanier** [comment]
Somehow django-backend already exists on PyPI, althouth it is not listed. Seems like this won't be easy.

**Comment by ddanier** [comment]
@gregmuellegger Did you encounter such a problem before? Any tips?

**Comment by gregmuellegger** [comment]
Unfortunatelly not, what error do you get? Maybe a message to the PyPI maintainers might be worth a try. I think there shouldn't be a reserved name which does not have a project page at https://pypi.python.org/pypi/django-backend/

**Comment by ddanier** [comment]
The error is:
Server response (403): You are not allowed to store 'django-backend' package information

I think the package exists, as https://pypi.python.org/pypi/django_backend/ redirects to the django-backend-URL. As you noted this shouldn't be happening.

I'll try to write them the next days, but as far as I can see all communication is organiszed over sourceforge. Sound unnecessary complicated.

**Comment by ddanier** [comment]
https://bitbucket.org/pypa/pypi/issues/343/cannot-register-django-backend

**Comment by ddanier** [comment]
Seems to be more complicated than expected:
https://bitbucket.org/pypa/pypi/issues/343/cannot-register-django-backend

Perhaps we could rename the PyPI release? Ideas? I have none I would like… :)

**Comment by gregmuellegger** [comment]
django-superbackend, django-backend2, the-real-backend, one-backend-to-rule-them-all?

**Comment by ddanier** [comment]
Or simply something like django_backend_package? "pip install get_django_backend_package"

**Comment by gregmuellegger** [comment]
`django_backend_team23` is a little to brandy or misleading, is it?

`django_backend_package` is a good idea I think. Let's go with it until we find a better solution. We can add a quick little note about the issue to the README.

**Comment by gregmuellegger** [comment]
Another thought: Backend is used very differently in the Django world (more describing pluggable solutions like AuthBackend, EmailBackend, etc). Maybe we should clarify the purpose of this backend in the name: `django-admin-backend`

We wouldn't change the python module name though, and stick to `django_backend` in the code.

**Comment by ddanier** [comment]
We could try django-admin-backend first, if thats not free I would stick to django-backend-package. Please prepare everything :)

**Comment by gregmuellegger** [comment]
Everything ready to go. You can try a `python setup.py register` to get the `django-admin-backend` name.

**Comment by ddanier** [comment]
Done :)
