### ISSUE TITLE
Remove django_ajax dependency

### ISSUE THREAD

**Issue by ddanier** [team23/django_backend#3]
Seems not to be necessary.

@gregmuellegger Any objections to just remove it? I found no usage of django_ajax in the code.

**Comment by gregmuellegger** [comment]
Nope, I think we used it to pass a `CONFIG` variable into the templates. But we don't have this anymore after we have ditched support for object locking.

**Comment by ddanier** [comment]
Right...but if I look at a clean install CONFIG just contains:

    var CONFIG = {"STATIC_URL": "/static/", "MEDIA_URL": "/media/"};

So this seems to be pretty unused. The only reference I find is this:
https://github.com/team23/django_backend/blob/master/django_backend/static/django_backend/js/require-init.js#L2
(Which could easily replaced)

Or am I missing something? Isn't object locking something we stripped of django_backend already anyways?

The thing is that django_ajax needs configuration, too. So the setup process is more complicated than it should be. In short you need to add the app, put the correct context processors to AJAX_CONFIG_PROCESSORS and put django_ajax inside the TEMPLATE_CONTEXT_PROCESSORS. As this is not documented and more complicated than necessary most users will fail to install django_backend on the first try (even with docs).

In additions using django_ajax will allow users to break django_backend by just playing with configuration (for example if you remove "django_ajax.ajax_processors.static" from AJAX_CONFIG_PROCESSORS -> require.js will break without this). All this could easily be avoided.

So I'm +1 for removing the dependency. Should I just implement the necessary changes? ;-)

**Comment by ddanier** [comment]
Sorry misread your comment about locking.

**Comment by gregmuellegger** [comment]
+1 go for it. I agree that its obsolete now
Am 04.10.2015 17:29 schrieb "David Danier" <notifications@github.com>:

**Comment by ddanier** [comment]
Fixed in edb33c01
