### ISSUE TITLE
Make sure the inline backend for SelectRelatedField can be overwritten

### ISSUE THREAD

**Issue by ddanier** [team23/django_backend#6]
If you extend SelectRelatedField to return a different backend for inline editing (lightbox) the backend will then be replaced back to the default inline backend in the select_related.html-Template. If you remove the default inline backend completely the template will die with an exception.

See:
https://github.com/team23/django_backend/blob/master/django_backend/templates/django_backend/forms/select_related.html#L3

**Comment by gregmuellegger** [comment]
Fixed in 0.4.0

**Comment by ddanier** [comment]
Yeah! 👍
